import fs from "node:fs";
import path from "node:path";
import os from "node:os";
import { simpleGit } from "simple-git";
import { createLogger } from "../../utils/logger.js";
import {
  getCloneUrl,
  getInstallationToken,
  createPullRequest,
  mergePullRequest,
  deleteBranch,
} from "../../services/github.js";
import { GitHubContentService } from "../../services/github-content.js";
import { GitHubContentReader } from "../readers/github.js";
import type { ContentReader } from "../../services/sync.js";
import type { SiteConnector, WriteResult, PublishResult, UnpublishResult } from "./types.js";
import type { Article, ArticleVersion, Project } from "../../models/types.js";

const log = createLogger("connector:github");

interface GitHubConfig {
  installationId: number;
  owner: string;
  repo: string;
  branch: string;
  contentPath: string;
  assetsPath: string;
}

/**
 * GitHub Site Connector.
 *
 * Read:    GitHub Contents API (no clone)
 * Write:   Clone → branch → commit → push → PR
 * Publish: Merge PR → delete branch
 */
export class GitHubSiteConnector implements SiteConnector {
  readonly platform = "github";
  private ghContent = new GitHubContentService();

  constructor(private config: GitHubConfig) {}

  createReader(): ContentReader {
    return new GitHubContentReader(this.ghContent, {
      installationId: this.config.installationId,
      owner: this.config.owner,
      repo: this.config.repo,
      branch: this.config.branch,
      contentPath: this.config.contentPath,
    });
  }

  async write(
    project: Project,
    article: Article,
    versions: ArticleVersion[],
    versionDir: string,
  ): Promise<WriteResult> {
    const { installationId, owner, repo, branch, contentPath, assetsPath } = this.config;

    const repoUrl = await getCloneUrl(installationId, owner, repo);
    const filesWritten: string[] = [];
    const workDir = path.join(os.tmpdir(), `flowboost-delivery-${article.id}`);

    try {
      // Clean up any previous attempt
      if (fs.existsSync(workDir)) {
        fs.rmSync(workDir, { recursive: true });
      }

      // Clone
      log.info({ branch }, "cloning repository");
      const git = simpleGit();
      await git.clone(repoUrl, workDir, ["--branch", branch, "--depth", "1"]);
      const repoGit = simpleGit(workDir);

      // Feature branch
      const branchName = `content/${article.translationKey}`;
      await repoGit.checkoutLocalBranch(branchName);

      // Copy files
      for (const version of versions) {
        const sourceContent = path.join(versionDir, "content", version.lang, `${version.slug}.md`);
        const targetContent = path.join(workDir, contentPath, version.lang, `${version.slug}.md`);

        if (fs.existsSync(sourceContent)) {
          fs.mkdirSync(path.dirname(targetContent), { recursive: true });
          fs.copyFileSync(sourceContent, targetContent);
          filesWritten.push(path.join(contentPath, version.lang, `${version.slug}.md`));
        }

        const sourceAssetsDir = path.join(versionDir, "assets", version.lang);
        if (fs.existsSync(sourceAssetsDir)) {
          const targetAssetsDir = path.join(workDir, assetsPath, version.lang);
          fs.mkdirSync(targetAssetsDir, { recursive: true });
          for (const file of fs.readdirSync(sourceAssetsDir)) {
            fs.copyFileSync(
              path.join(sourceAssetsDir, file),
              path.join(targetAssetsDir, file),
            );
            filesWritten.push(path.join(assetsPath, version.lang, file));
          }
        }
      }

      if (filesWritten.length === 0) {
        return { success: false, ref: "", published: false, filesWritten: [], error: "No files to deliver" };
      }

      // Commit + push
      await repoGit.add(filesWritten);
      const languages = versions.map((v) => v.lang).join(", ");
      const commitMessage = `feat(content): add ${article.translationKey} (${languages})`;
      await repoGit.commit(commitMessage);
      await repoGit.push("origin", branchName, ["--set-upstream"]);

      const logResult = await repoGit.log({ maxCount: 1 });
      const commitHash = logResult.latest?.hash;

      // Create PR
      let prNumber = "";
      let prUrl: string | undefined;

      try {
        const pr = await createPullRequest(
          installationId, owner, repo,
          branchName, branch,
          commitMessage,
          `New article: **${article.translationKey}**\n\nLanguages: ${languages}\nFiles: ${filesWritten.length}\n\nGenerated by FlowBoost.`,
        );
        prNumber = String(pr.number);
        prUrl = pr.url;
        log.info({ prNumber, prUrl }, "pull request created");
      } catch (prError) {
        log.warn({ err: prError }, "PR creation failed (files still pushed)");
        prNumber = branchName; // Fallback: use branch name as ref
      }

      // Cleanup workdir
      fs.rmSync(workDir, { recursive: true });

      return {
        success: true,
        ref: prNumber,
        url: prUrl,
        published: false, // GitHub needs explicit publish (PR merge)
        filesWritten,
        commitHash,
      };
    } catch (error) {
      const msg = error instanceof Error ? error.message : String(error);
      log.error({ err: error }, "github write failed");
      if (fs.existsSync(workDir)) {
        fs.rmSync(workDir, { recursive: true });
      }
      return { success: false, ref: "", published: false, filesWritten, error: msg };
    }
  }

  async update(
    project: Project,
    article: Article,
    versions: ArticleVersion[],
    versionDir: string,
    _previousRef?: string,
  ): Promise<WriteResult> {
    // For GitHub, update is the same as write — creates a new PR with updated content
    // The branch name includes "-update" to differentiate from initial delivery
    const { installationId, owner, repo, branch, contentPath, assetsPath } = this.config;
    const repoUrl = await getCloneUrl(installationId, owner, repo);
    const filesWritten: string[] = [];
    const workDir = path.join(os.tmpdir(), `flowboost-update-${article.id}`);

    try {
      if (fs.existsSync(workDir)) {
        fs.rmSync(workDir, { recursive: true });
      }

      log.info({ branch }, "cloning repository for update");
      const git = simpleGit();
      await git.clone(repoUrl, workDir, ["--branch", branch, "--depth", "1"]);
      const repoGit = simpleGit(workDir);

      const branchName = `content/${article.translationKey}-update-${Date.now()}`;
      await repoGit.checkoutLocalBranch(branchName);

      for (const version of versions) {
        const sourceContent = path.join(versionDir, "content", version.lang, `${version.slug}.md`);
        const targetContent = path.join(workDir, contentPath, version.lang, `${version.slug}.md`);

        if (fs.existsSync(sourceContent)) {
          fs.mkdirSync(path.dirname(targetContent), { recursive: true });
          fs.copyFileSync(sourceContent, targetContent);
          filesWritten.push(path.join(contentPath, version.lang, `${version.slug}.md`));
        }

        const sourceAssetsDir = path.join(versionDir, "assets", version.lang);
        if (fs.existsSync(sourceAssetsDir)) {
          const targetAssetsDir = path.join(workDir, assetsPath, version.lang);
          fs.mkdirSync(targetAssetsDir, { recursive: true });
          for (const file of fs.readdirSync(sourceAssetsDir)) {
            fs.copyFileSync(
              path.join(sourceAssetsDir, file),
              path.join(targetAssetsDir, file),
            );
            filesWritten.push(path.join(assetsPath, version.lang, file));
          }
        }
      }

      if (filesWritten.length === 0) {
        return { success: false, ref: "", published: false, filesWritten: [], error: "No files to update" };
      }

      await repoGit.add(filesWritten);
      const languages = versions.map((v) => v.lang).join(", ");
      const commitMessage = `fix(content): update ${article.translationKey} (${languages})`;
      await repoGit.commit(commitMessage);
      await repoGit.push("origin", branchName, ["--set-upstream"]);

      const logResult = await repoGit.log({ maxCount: 1 });
      const commitHash = logResult.latest?.hash;

      let prNumber = "";
      let prUrl: string | undefined;

      try {
        const pr = await createPullRequest(
          installationId, owner, repo,
          branchName, branch,
          commitMessage,
          `Update article: **${article.translationKey}**\n\nLanguages: ${languages}\nFiles: ${filesWritten.length}\n\nUpdated by FlowBoost.`,
        );
        prNumber = String(pr.number);
        prUrl = pr.url;
      } catch (prError) {
        log.warn({ err: prError }, "PR creation failed for update");
        prNumber = branchName;
      }

      fs.rmSync(workDir, { recursive: true });

      return {
        success: true,
        ref: prNumber,
        url: prUrl,
        published: false,
        filesWritten,
        commitHash,
      };
    } catch (error) {
      const msg = error instanceof Error ? error.message : String(error);
      log.error({ err: error }, "github update failed");
      if (fs.existsSync(workDir)) fs.rmSync(workDir, { recursive: true });
      return { success: false, ref: "", published: false, filesWritten, error: msg };
    }
  }

  async unpublish(ref: string, _options?: { soft?: boolean }): Promise<UnpublishResult> {
    // For GitHub, unpublish = create a PR that deletes the content files
    // This is a placeholder — full implementation would need to know which files to delete
    log.info({ ref }, "unpublish requested (GitHub — manual PR deletion recommended)");
    return {
      success: true,
      ref,
    };
  }

  async publish(writeRef: string): Promise<PublishResult> {
    const { installationId, owner, repo } = this.config;
    const prNumber = Number(writeRef);

    if (!prNumber) {
      return { success: false, error: `Invalid PR reference: ${writeRef}` };
    }

    try {
      // Merge PR (squash for clean history)
      const { sha } = await mergePullRequest(
        installationId, owner, repo, prNumber, "squash",
      );

      // Delete feature branch
      try {
        // Find branch name from PR
        const branchName = await this.getPrBranch(prNumber);
        if (branchName) {
          await deleteBranch(installationId, owner, repo, branchName);
        }
      } catch (branchErr) {
        log.warn({ err: branchErr }, "branch deletion failed (may be auto-deleted)");
      }

      log.info({ prNumber, sha }, "article published via PR merge");

      return { success: true, ref: sha };
    } catch (error) {
      const msg = error instanceof Error ? error.message : String(error);
      log.error({ err: error, prNumber }, "publish failed");
      return { success: false, error: msg };
    }
  }

  private async getPrBranch(prNumber: number): Promise<string | null> {
    const { installationId, owner, repo } = this.config;
    const token = await getInstallationToken(installationId);

    const res = await fetch(
      `https://api.github.com/repos/${owner}/${repo}/pulls/${prNumber}`,
      {
        headers: {
          Authorization: `Bearer ${token}`,
          Accept: "application/vnd.github+json",
          "X-GitHub-Api-Version": "2022-11-28",
        },
      },
    );

    if (!res.ok) return null;
    const pr = (await res.json()) as { head: { ref: string } };
    return pr.head.ref;
  }
}
